### ISSUE TITLE
[Idea] Confirmation on refresh or navigate away from flow

### ISSUE THREAD

**Issue by sgraden** [signalnerve/deploy.workers.cloudflare.com#38]
I don't see this on vercel or netlify (though didn't test every point in the flow), but what are y'alls opinion on a confirmation dialog appearing if the user tries to do something like close tab, navigate back, or refresh page as it may "lose data". Happens on a lot of forms as well as gmail and such.

![image](https://user-images.githubusercontent.com/6685872/88954357-e42b7200-d25f-11ea-8ee4-f84c9c5e394d.png)

**Comment by signalnerve** [comment]
we shouldn't need to do this! because we use a form for account id/api token now, it'll put up a prompt if you try and refresh while it's still on the page. we also cache step progress as best we can (as well as account id, but not local storage) so you should be able to land back on the same step in the deploy flow without being disrupted if you do leave or refresh.

closing this for now, but if i'm wrong or forgot something (very possible) we can re-open this after today's QA session
